/*
 Copyright 2012 StackMob Inc.
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
 http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
(function(){function j(a){for(var a=a+"=",b=document.cookie.split(";"),e=0;e<b.length;e++){for(var d=b[e];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null}var b=this;window.StackMob=b.StackMob={DEFAULT_API_VERSION:0,DEFAULT_LOGIN_SCHEMA:"user",DEFAULT_LOGIN_FIELD:"username",DEFAULT_PASSWORD_FIELD:"password",EARTH_RADIANS_MI:3956.6,EARTH_RADIANS_KM:6367.5,FORCE_CREATE_REQUEST:"stackmob_force_create_request",ARRAY_FIELDNAME:"stackmob_array_fieldname",
ARRAY_VALUES:"stackmob_array_values",CASCADE_DELETE:"stackmob_cascade_delete",HARD_DELETE:!0,SOFT_DELETE:!1,apiVersion:0,sdkVersion:"0.5.2",publicKey:null,loggedInCookie:null,loggedInUser:null,Storage:{STORAGE_PREFIX:"stackmob.",persist:function(a,b){localStorage&&localStorage.setItem(this.STORAGE_PREFIX+a,b)},retrieve:function(a){if(localStorage)return localStorage.getItem(this.STORAGE_PREFIX+a);null},remove:function(a){localStorage&&localStorage.removeItem(this.STORAGE_PREFIX+a)}},getLoggedInUser:function(){var a=
!this.isOAuth2Mode()&&this.Storage.retrieve(this.loggedInUserKey)||this.Storage.retrieve("oauth2_user");return this.isLoggedIn()&&a?a:null},isLoggedIn:function(){return null!=j(StackMob.loggedInCookie)&&!this.isLoggedOut()||this.hasValidOAuth()},isUserLoggedIn:function(a){return a==this.getLoggedInUser()},isLoggedOut:function(){if(this.isOAuth2Mode())return!this.hasValidOAuth();var a=j(StackMob.loggedInCookie);if(!a)return!0;try{return JSON.parse(a)}catch(b){return!1}},getScheme:function(){return!0===
this.secure?"https":"http"},getDevAPIBase:function(){return"undefined"!==typeof PhoneGap?this.getScheme()+"://api.mob1.stackmob.com/":!0===this.fullURL?this.getScheme()+"://dev."+this.appName+"."+this.clientSubdomain+".stackmobapp.com/":"/"},getProdAPIBase:function(){return"undefined"!==typeof PhoneGap?this.getScheme()+"://api.mob1.stackmob.com/":!0===this.fullURL?this.getScheme()+"://"+this.appName+"."+this.clientSubdomain+".stackmobapp.com/":"/"},getBaseURL:function(){return StackMob.apiURL||(StackMob.fullURL?
0===StackMob.apiVersion?StackMob.getDevAPIBase():StackMob.getProdAPIBase():window.location.protocol+"//"+window.location.hostname+":"+window.location.port+"/")},throwError:function(a){throw Error(a);},urlError:function(){this.throwError('A "url" property or function must be specified')},requirePublicKey:function(){StackMob.publicKey||this.throwError("Error: This requires that you initialize StackMob with a public key.")},isOAuth2Mode:function(){return!isNaN(StackMob.publicKey&&!StackMob.privateKey)},
prepareCredsForSaving:function(a,b,e,d){e=(new Date).getTime()+1E3*e;return{oauth2_accessToken:a,oauth2_macKey:b,oauth2_expires:e,oauth2_user:d}},saveOAuthCredentials:function(a){var b=a.oauth2_accessToken;this.Storage.retrieve("oauth2_accessToken")!=b&&this.Storage.persist("oauth2_expires",a.oauth2_expires);this.Storage.persist("oauth2_accessToken",b);this.Storage.persist("oauth2_macKey",a.oauth2_macKey);this.Storage.persist("oauth2_user",a.oauth2_user)},hasValidOAuth:function(){if(!this.isOAuth2Mode())return!1;
var a=this.getOAuthCredentials(),b=a.oauth2_expires||0;return _.all([a.oauth2_accessToken,a.oauth2_macKey,b],_.identity)&&(new Date).getTime()<=b},getOAuthCredentials:function(){var a=StackMob.Storage.retrieve("oauth2_accessToken"),b=StackMob.Storage.retrieve("oauth2_macKey"),e=StackMob.Storage.retrieve("oauth2_expires");return{oauth2_accessToken:a,oauth2_macKey:b,oauth2_expires:e}},getOAuthExpireTime:function(){var a=this.Storage.retrieve("oauth2_expires");return a?parseInt(a):null},METHOD_MAP:{create:"POST",
read:"GET",update:"PUT","delete":"DELETE",addRelationship:"POST",appendAndSave:"PUT",deleteAndSave:"DELETE",login:"GET",accessToken:"POST",logout:"GET",forgotPassword:"POST",loginWithTempAndSetNewPassword:"GET",resetPassword:"POST",loginWithFacebookToken:"GET",createUserWithFacebook:"GET",linkUserWithFacebook:"GET",cc:"GET"},getProperty:function(a,b){return!a||!a[b]?null:_.isFunction(a[b])?a[b]():a[b]},init:function(a){a=a||{};this.initStart(a);this.userSchema=a.userSchema||this.DEFAULT_LOGIN_SCHEMA;
this.loginField=a.loginField||this.DEFAULT_LOGIN_FIELD;this.passwordField=a.passwordField||this.DEFAULT_PASSWORD_FIELD;this.newPasswordField=a.newPasswordField||"new_password";this.apiVersion=a.apiVersion||this.DEFAULT_API_VERSION;this.appName=this.getProperty(a,"appName")||this.throwError("An appName must be specified");this.clientSubdomain=this.getProperty(a,"clientSubdomain");this.loggedInCookie="session_"+this.appName;this.loggedInUserKey=this.loggedInCookie+"_user";this.publicKey=a.publicKey;
this.apiURL=a.apiURL;if(this.isOAuth2Mode()&&(!b.Crypto||b.Crypto&&!b.Crypto.HMAC)){var c=document.createElement("script");c.setAttribute("src","https://s3.amazonaws.com/static.stackmob.com/js/2.5.3-crypto-sha1-hmac.js");c.setAttribute("type","text/javascript");var e=!1,d=function(){e||(e=!0)};c.onload=d;c.onreadystatechange=d;document.getElementsByTagName("head")[0].appendChild(c)}this.oauth2targetdomain=a.oauth2targetdomain||this.oauth2targetdomain||"www.stackmob.com";this.secure=!0===a.secure;
this.fullURL=!0===a.fullURL||"undefined"!==typeof PhoneGap||this.fullURL;this.ajax=a.ajax||this.ajax;this.debug=0===this.apiVersion;this.urlRoot=a.urlRoot||this.getBaseURL();this.initEnd(a);return this},initStart:function(){},initEnd:function(){}}}).call(this);
(function(){var j=this;_.extend(StackMob,{isSencha:function(){return j.Ext},isZepto:function(){return j.Zepto},initEnd:function(){StackMob.Model=Backbone.Model.extend({urlRoot:StackMob.urlRoot,url:function(){var b=StackMob.urlRoot||StackMob.urlError();return b+=this.schemaName},getPrimaryKeyField:function(){return this.schemaName+"_id"},constructor:function(){this.setIDAttribute();Backbone.Model.prototype.constructor.apply(this,arguments)},initialize:function(){StackMob.getProperty(this,"schemaName")||
StackMob.throwError("A schemaName must be defined");this.setIDAttribute()},setIDAttribute:function(){this.idAttribute=this.getPrimaryKeyField()},parse:function(b){return!b||b&&(!b.text||""==b.text)?b:JSON.parse(b.text)},sync:function(b,a,c){StackMob.sync.call(this,b,this,c)},create:function(b){var a={};a[StackMob.FORCE_CREATE_REQUEST]=!0;_.extend(a,b);this.save(null,a)},query:function(b,a){a=a||{};_.extend(a,{query:b});this.fetch(a)},fetchExpanded:function(b,a){(0>b||3<b)&&StackMob.throwError("Depth must be between 0 and 3 inclusive.");
var c={};_.extend(c,a);c.data=c.data||{};c.data._expand=b;this.fetch(c)},getAsModel:function(b,a){var c=this.get(b);return c?_.isArray(c)?_.map(c,function(b){return new a(b)}):new a(c):{}},appendAndCreate:function(b,a,c){this.addRelationship(b,a,c)},addRelationship:function(b,a,c){c=c||{};c[StackMob.ARRAY_FIELDNAME]=b;c[StackMob.ARRAY_VALUES]=a;StackMob.sync.call(this,"addRelationship",this,c)},appendAndSave:function(b,a,c){c=c||{};c[StackMob.ARRAY_FIELDNAME]=b;c[StackMob.ARRAY_VALUES]=a;StackMob.sync.call(this,
"appendAndSave",this,c)},deleteAndSave:function(b,a,c,e){e=e||{};e[StackMob.ARRAY_FIELDNAME]=b;e[StackMob.ARRAY_VALUES]=a;e[StackMob.CASCADE_DELETE]=c;StackMob.sync.call(this,"deleteAndSave",this,e)},setBinaryFile:function(b,a,c,e){this.set(b,"Content-Type: "+c+"\nContent-Disposition: attachment; filename="+a+"\nContent-Transfer-Encoding: base64\n\n"+e)},incrementOnSave:function(b,a){this.attributes[this.idAttribute]?(this.attributes[b]&&delete this.attributes[b],this.set(b+"[inc]",a)):StackMob.throwError("Please specify an id for the row you wish to update. When creating a new instance of your object, you need to pass in JSON that includes the id field and value (e.g. var user = new StackMob.User({ username: 'chucknorris' });)  Or, for custom objects: var todoInstance = new Todo({todo_id : '1234'})")},
decrementOnSave:function(b,a){this.incrementOnSave(b,-1*a)}});StackMob.Collection=Backbone.Collection.extend({initialize:function(){this.model||StackMob.throwError("Please specify a StackMob.Model for this collection. e.g., var Items = StackMob.Collection.extend({ model: Item });");this.schemaName=(new this.model).schemaName},url:function(){var b=StackMob.urlRoot||StackMob.urlError();return b+=this.schemaName},parse:function(b){return!b||b&&(!b.text||""==b.text)?b:JSON.parse(b.text)},sync:function(b,
a,c){StackMob.sync.call(this,b,this,c)},query:function(b,a){a=a||{};_.extend(a,{query:b});this.fetch(a)},create:function(b,a){var c={};c[StackMob.FORCE_CREATE_REQUEST]=!0;_.extend(c,a);Backbone.Collection.prototype.create.call(this,b,c)},count:function(b,a){b=b||new StackMob.Collection.Query;a=a||{};a.stackmob_count=!0;var c=a.success;a.success=function(a){if(a&&a.getAllResponseHeaders){var a=a.getResponseHeader("Content-Range"),b=-1;a&&(b=a.substring(a.indexOf("/")+1,a.length));c&&c(b)}else c(a)};
b.setRange&&(a.query=b.setRange(0,0));return(this.sync||Backbone.sync).call(this,"query",this,a)}});StackMob.User=StackMob.Model.extend({idAttribute:StackMob.loginField,schemaName:StackMob.userSchema,getPrimaryKeyField:function(){return StackMob.loginField},isLoggedIn:function(){return StackMob.isUserLoggedIn(this.get(StackMob.loginField))},login:function(b,a){a=a||{};isNaN(b);a.data=a.data||{};a.data[StackMob.loginField]=this.get(StackMob.loginField);a.data[StackMob.passwordField]=this.get(StackMob.passwordField);
StackMob.isOAuth2Mode()&&(a.data.token_type="mac");var c=this;a.stackmob_onaccessToken=function(a){StackMob.isOAuth2Mode()&&(a=StackMob.prepareCredsForSaving(a.access_token,a.mac_key,a.expires_in,c.get(StackMob.loginField)),StackMob.saveOAuthCredentials(a));StackMob.Storage.persist(StackMob.loggedInUserKey,c.get(StackMob.loginField))};(this.sync||Backbone.sync).call(this,StackMob.isOAuth2Mode()?"accessToken":"login",this,a)},logout:function(b){b=b||{};b.data=b.data||{};b.stackmob_onlogout=function(){StackMob.Storage.remove(StackMob.loggedInUserKey);
StackMob.Storage.remove("oauth2_accessToken");StackMob.Storage.remove("oauth2_macKey");StackMob.Storage.remove("oauth2_expires");StackMob.Storage.remove("oauth2_user")};(this.sync||Backbone.sync).call(this,"logout",this,b)},loginWithFacebookToken:function(b,a,c){c=c||{};c.data=c.data||{};_.extend(c.data,{fb_at:b});(this.sync||Backbone.sync).call(this,"facebookLogin",this,c)},createUserWithFacebook:function(b,a){a=a||{};a.data=a.data||{};_.extend(a.data,{fb_at:b});a.data[StackMob.loginField]=a[StackMob.loginField]||
this.get(StackMob.loginField);(this.sync||Backbone.sync).call(this,"createUserWithFacebook",this,a)},linkUserWithFacebook:function(b,a){a=a||{};a.data=a.data||{};_.extend(a.data,{fb_at:b});(this.sync||Backbone.sync).call(this,"linkUserWithFacebook",this,a)},loginWithTempAndSetNewPassword:function(b,a,c,e){e=e||{};e.data=e.data||{};b={};b[StackMob.passwordField]=oldPassword;this.set(b);e.data[StackMob.newPasswordField]=a;this.login(c,e)},forgotPassword:function(b){b=b||{};b.data=b.data||{};b.data[StackMob.loginField]=
this.get(StackMob.loginField);(this.sync||Backbone.sync).call(this,"forgotPassword",this,b)},resetPassword:function(b,a,c){c=c||{};c.data=c.data||{};c.data.old={password:b};c.data["new"]={password:a};(this.sync||Backbone.sync).call(this,"resetPassword",this,c)}});StackMob.Users=StackMob.Collection.extend({model:StackMob.User});StackMob.GeoPoint=function(b,a){_.isNumber(b)?(this.lat=b,this.lon=a):(this.lat=b.lat,this.lon=b.lon)};StackMob.GeoPoint.prototype.toJSON=function(){return{lat:this.lat,lon:this.lon}};
StackMob.Model.Query=function(){this.selectFields=[];this.params={}};_.extend(StackMob.Model.Query.prototype,{select:function(b){this.selectFields.push(b);return this},setExpand:function(b){this.params._expand=b;return this}});StackMob.Collection.Query=function(){this.params={};this.orderBy=[];this.range=null};StackMob.Collection.Query.prototype=new StackMob.Model.Query;StackMob.Collection.Query.prototype.constructor=StackMob.Collection.Query;_.extend(StackMob.Collection.Query.prototype,{addParam:function(b,
a){this.params[b]=a;return this},equals:function(b,a){this.params[b]=a;return this},lt:function(b,a){this.params[b+"[lt]"]=a;return this},lte:function(b,a){this.params[b+"[lte]"]=a;return this},gt:function(b,a){this.params[b+"[gt]"]=a;return this},gte:function(b,a){this.params[b+"[gte]"]=a;return this},notEquals:function(b,a){this.params[b+"[ne]"]=a;return this},isNull:function(b){this.params[b+"[null]"]=!0;return this},isNotNull:function(b){this.params[b+"[null]"]=!1;return this},mustBeOneOf:function(b,
a){var c="";if(_.isArray(a))for(var e=a.length,d=0;d<e;d++)c+=a[d],d+1<e&&(c+=",");else c=a;this.params[b+"[in]"]=c;return this},orderAsc:function(b){this.orderBy.push(b+":asc");return this},orderDesc:function(b){this.orderBy.push(b+":desc");return this},setRange:function(b,a){this.range={start:b,end:a};return this},mustBeNear:function(b,a,c){this.params[b+"[near]"]=a.lat+","+a.lon+","+c;return this},mustBeNearMi:function(b,a,c){this.mustBeNear(b,a,c/StackMob.EARTH_RADIANS_MI);return this},mustBeNearKm:function(b,
a,c){this.mustBeNear(b,a,c/StackMob.EARTH_RADIANS_KM);return this},isWithin:function(b,a,c){this.params[b+"[within]"]=a.lat+","+a.lon+","+c;return this},isWithinMi:function(b,a,c){this.isWithin(b,a,c/StackMob.EARTH_RADIANS_MI);return this},isWithinKm:function(b,a,c){this.isWithin(b,a,c/StackMob.EARTH_RADIANS_KM);return this},isWithinBox:function(b,a,c){this.params[b+"[within]"]=a.lat+","+a.lon+","+c.lat+","+c.lon;return this}})},cc:function(b,a,c){this.customcode(b,a,c)},customcode:function(b,a,c){c=
c||{};c.data=c.data||{};_.extend(c.data,a);c.url=this.debug?this.getDevAPIBase():this.getProdAPIBase();this.sync.call(StackMob,b,null,c)},sync:function(b,a,c){var c=c||{},e=!0===c[StackMob.FORCE_CREATE_REQUEST];e&&(b="create");var d=_.extend({type:c.httpVerb||StackMob.METHOD_MAP[b]||"GET",dataType:"json"},c);d.data=d.data||{};d.url||a&&(d.url=StackMob.getProperty(a,"url"));var f="cc"!=b,h=a&&a.isNew&&!a.isNew(),e=!e,g="addRelationship"==b||"appendAndSave"==b||"deleteAndSave"==b;if(_.include("create update delete read query deleteAndSave appendAndSave addRelationship".split(" "),
b)){if(g||f&&h&&e)d.url+=("/"==d.url.charAt(d.url.length-1)?"":"/")+encodeURIComponent(a.get(a.getPrimaryKeyField())),g&&(d.url+="/"+c[StackMob.ARRAY_FIELDNAME]),"deleteAndSave"==b&&(f="",f=_.isArray(c[StackMob.ARRAY_VALUES])?_.map(c[StackMob.ARRAY_VALUES],function(a){return encodeURIComponent(a)}).join(","):encodeURIComponent(c[StackMob.ARRAY_VALUES]),d.url+="/"+f)}else d.url+=("/"==d.url.charAt(d.url.length-1)?"":"/")+b;f=c;d.headers=d.headers||{};d.headers=_.extend({Accept:"application/vnd.stackmob+json; version="+
StackMob.apiVersion},d.headers);_.extend(d.headers,{"X-StackMob-User-Agent":"StackMob (JS; "+StackMob.sdkVersion+")/"+StackMob.appName});StackMob.publicKey&&!StackMob.privateKey?(d.headers["X-StackMob-API-Key"]=StackMob.publicKey,d.headers["X-StackMob-Proxy-Plain"]="stackmob-api"):d.headers["X-StackMob-Proxy"]="stackmob-api";StackMob.isOAuth2Mode()&&"accessToken"===b?d.contentType="application/x-www-form-urlencoded":_.include(["PUT","POST"],StackMob.METHOD_MAP[b])&&(d.contentType=d.contentType||"application/json");
isNaN(f[StackMob.CASCADE_DELETE])||(d.headers["X-StackMob-CascadeDelete"]=!0==f[StackMob.CASCADE_DELETE]);if(f.query&&(f=d.query||throwError("No StackMobQuery object provided to the query call."),f.selectFields&&0<f.selectFields.length&&(d.headers["X-StackMob-Select"]=f.selectFields.join()),f.range&&(d.headers.Range="objects="+f.range.start+"-"+f.range.end),_.extend(d.data,f.params),f.orderBy&&0<f.orderBy.length)){f=f.orderBy;h="";e=f.length;for(g=0;g<e;g++)h+=f[g],g+1<e&&(h+=",");d.headers["X-StackMob-OrderBy"]=
h}f=b;h=function(a){return _.map(_.keys(a),function(b){return b+"="+encodeURIComponent(a[b])}).join("&")};c=c||{};StackMob.isOAuth2Mode()&&"accessToken"===f?d.data=h(d.data):"POST"==d.type||"PUT"==d.type?"resetPassword"==f||"forgotPassword"==f?d.data=JSON.stringify(d.data):"addRelationship"==f||"appendAndSave"==f?c&&c[StackMob.ARRAY_VALUES]&&(d.data=JSON.stringify(c[StackMob.ARRAY_VALUES])):a?(c=a.toJSON(),delete c.lastmoddate,delete c.createddate,d.data=JSON.stringify(_.extend(c,d.data))):d.data=
JSON.stringify(d.data):("GET"==d.type&&!_.isEmpty(d.data)&&(d.url+="?",c=h(d.data),d.url+=c),delete d.data);c=d||{};c.processData=!1;c.accepts=c.headers.Accept;e=b;if(!a||!a.schemaName||!(a.schemaName==StackMob.userSchema&&_.include(["create","accessToken"],e)))if(c=StackMob.getBaseURL(),f=d.url.replace(RegExp(c,"g"),"/"),h=c.replace(RegExp("^http://|^https://","g"),"").replace(/\//,""),c=StackMob.Storage.retrieve("oauth2_accessToken"),g=StackMob.Storage.retrieve("oauth2_macKey"),StackMob.Storage.retrieve("oauth2_expires"),
StackMob.isOAuth2Mode()&&c&&g){for(var i=StackMob.METHOD_MAP[e]||"GET",e=h.split(":"),k=1<e.length?e[0]:h,j=1<e.length?e[1]:80,h=Math.round((new Date).getTime()/1E3),e="n"+Math.round(1E4*Math.random()),f=Crypto.HMAC(Crypto.SHA1,h+"\n"+e+"\n"+i+"\n"+f+"\n"+k+"\n"+j+"\n\n",g,{asBytes:!0}),g="",i=0;i<f.length;i++)g+=String.fromCharCode(f[i]);f=btoa(g);(c='MAC id="'+c+'",ts="'+h+'",nonce="'+e+'",mac="'+f+'"')&&(d.headers.Authorization=c)}StackMob.makeAPICall(a,d,b)},makeAPICall:function(b,a,c){return StackMob.ajax?
StackMob.ajax(b,a,c):StackMob.isSencha()?StackMob.ajaxOptions.sencha(b,a,c):StackMob.isZepto()?StackMob.ajaxOptions.zepto(b,a,c):StackMob.ajaxOptions.jquery(b,a,c)}})}).call(this);
(function(){var j=this.jQuery||this.Ext||this.Zepto;_.extend(StackMob,{ajaxOptions:{sencha:function(b,a,c){var e=a.success;a.success=function(d){var f=d&&d.responseText?JSON.parse(d.responseText):null;if(_.isFunction(a["stackmob_on"+c]))a["stackmob_on"+c](f);if(f)if(b.clear(),StackMob.isOAuth2Mode()&&"accessToken"===c&&f.stackmob)f=f.stackmob.user,e(f);else{if(!0===a.stackmob_count)e(d);else if(!b.set(f))return!1;e(b)}else e()};var d=a.error;a.error=function(a){var c=null;try{c=a.responseText?JSON.parse(a.responseText):
a}catch(f){}(function(a,b){d(b)}).call(StackMob,b,c)};var f={};f.url=a.url;f.headers=a.headers;f.params=a.data;f.success=a.success;f.failure=a.error;f.disableCaching=!1;f.method=a.type;return j.Ajax.request(f)},zepto:function(b,a,c){var e=a.success,d=function(d,f,h){f=d?JSON.parse(d):null;if(_.isFunction(a["stackmob_on"+c]))a["stackmob_on"+c](f);if(f)if(b.clear(),StackMob.isOAuth2Mode()&&"accessToken"===c&&f.stackmob)f=f.stackmob.user,e(f);else{if(!0===a.stackmob_count)e(h);else if(!b.set(f))return!1;
e(b)}else e()};a.success=d;var f=a.error,h=function(a){a=a.responseText?JSON.parse(a.responseText):a;(function(a,b){f(b)}).call(StackMob,b,a)};a.error=h;var g={};g.url=a.url;g.headers=a.headers;g.type=a.type;g.data=a.data;g.success=d;g.error=h;return j.ajax(g)},jquery:function(b,a,c){a.beforeSend=function(a,b){a.setRequestHeader("Accept",b.accepts);if(!_.isEmpty(b.headers))for(key in b.headers)a.setRequestHeader(key,b.headers[key])};var e=a.error;a.error=function(a){var c;if(a&&(a.responseText||a.text))c=
JSON.parse(a.responseText||a.text);(function(a,b){e&&e(b)}).call(StackMob,b,c)};var d=a.success;a.success=function(b,e,g){var i;b&&b.toJSON?i=b:b&&(b.responseText||b.text)?i=JSON.parse(b.responseText||b.text):b&&(i=b);!0===a.stackmob_count&&(i=g);if(_.isFunction(a["stackmob_on"+c]))a["stackmob_on"+c](i);d&&(StackMob.isOAuth2Mode()&&("accessToken"===c&&i.stackmob)&&(i=i.stackmob.user),d(i))};return j.ajax(a)}}})}).call(this);